### ISSUE TITLE
请求入口  或者源码

### ISSUE THREAD

**Issue by CGeekhl** [gy-games/shield#2]
由于论文选了大数据实时分析 的课题，    我想基于你的框架来写  ，希望能得到你的帮助，谢谢

**Comment by toryzen** [comment]
可以先参考此思路，这是Shield的初版设计，最终版虽有调整但整体思路一致，Shield开源还需要过段时间
http://www.toryzen.cn/2017/11/03/%E6%96%B0%E4%B8%80%E4%BB%A3CC%E9%98%B2%E7%81%AB%E5%A2%99-SHIELD2-0/
